### ISSUE TITLE
Compilation Error When Switching `language` to `chinese` in `ncs-thesis.cls`

### ISSUE THREAD

**Issue by NTU-CAE-David** [NTU-NCS-lab/ThesisWritingTemplate#3]
When I set `language` to `chinese` in `ncs-thesis.cls`, I encounter compilation errors. These errors do not occur when using `language = english`.

**Comment by sciyen** [comment]
@NTU-CAE-David Thank you for pointing out this bug! This error is caused by the conversion from the appendix number i.e., A, B, C, etc. to Chinese. This bug has been solved in b6442a7492ae94f2cf001972a628357e4e1bb6cf. 

I also noticed that the language of `\secref`, `\figref`, and `\eqref` commands are wrong in `chinese` mode, which is solved in 93a1f24f643a46e0c93b523455d1371ae1a9948b.

Please use `git pull` to apply the newest changes.
I really appreciate your contributions to reporting this bug.
